jwt:
  expiration: 86400000

aj:
  captcha:
    cache-type: local
    type: DEFAULT
    jigsaw: "classpath:images/jigsaw"
    pic-click: "classpath:images/pic-click"
    #右下角水印
    water-mark: TooBee
    #滑动拼图允许的误差范围，默认5像素
    slip-offset: 5
    #是否开启aes加密，默认false
    aes-status: true
    #干扰选项，1：数字，2：字母，3：数字+字母
    interference-options: 2
    #字体样式，1：宋体，2：微软雅黑，3：楷体
    font-style: 1
    #字体大小，默认25
    font-size: 25
    #是否开启历史数据清除，默认false
    history-data-clear-enable: false
    #是否开启请求频率限制，默认false
    req-frequency-limit-enable: false
    #验证失败几次后锁定
    req-get-lock-limit: 5
    #获取验证码锁超时时间，默认1000毫秒
    req-get-lock-seconds: 360
    # get 接口：一分钟内最大请求数
    req-get-minute-limit: 30
    # check 接口：一分钟内最大请求数
    req-check-minute-limit: 30
    # 本地缓存阈值，达到后自动清理（默认1000）
    cache-number: 1000
    # 定时清理过期缓存（秒），0=不清理（默认180秒）
    timing-clear: 180



spring:
  application:
    name:
      toobee-web-spring
  datasource:
    hikari:
      initialization-fail-timeout: 5000
      connection-timeout: 2000
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  security:
    user:
      name: admin
      password: 123456
  jpa:
    open-in-view: true
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /toobee
    username: toobee
    password: 123
  config:
    import: "optional:file:./custom.yml"

---


spring:
  config:
    activate:
      on-profile: prod
  web:
    resources:
      static-locations: []

---

spring:
  config:
    activate:
      on-profile: dev
  web:
    resources:
      static-locations: classpath:/static-dev/
  mvc:
    static-path-pattern: "/**"



